export let AllHeros = () => {
  let heros = [
    {
      name: 'Kathryn Murphy',
      phone: '(252) 555-0126',
      email: 'tanya.hill@example.com',
      date: 'March 6 ,2018',
      country: 'Saudi Arbia',
      company: "L'Oreal",
    },
    {
      name: 'Wade Warren',
      phone: '(671) 555-0110',
      email: 'dolars.champ@example.com',
      date: 'septemper 24 ,2017',
      country: 'Serpia',
      company: 'eBay',
    },
    {
      name: 'Devone lane',
      phone: '(209) 555-0104',
      email: 'sara.cruze@example.com',
      date: 'febraury 9 ,2015',
      country: 'Russian Federation',
      company: 'Gillete',
    },
    {
      name: 'Albert Flores',
      phone: '(808) 555-0111',
      email: 'danna.hill@example.com',
      date: 'Nuvamper 16 ,2014',
      country: 'Poland',
      company: 'Luis Vuitton',
    },
    {
      name: 'Jerome Bell',
      phone: '(505) 555-0125',
      email: 'tanya.Jerome@example.com',
      date: 'October 31 ,2017',
      country: 'Saudi Arbia',
      company: 'Facebook',
    },
    {
      name: 'Kathryn Murphy',
      phone: '(252) 555-0126',
      email: 'tanya.hill@example.com',
      date: 'March 6 ,2018',
      country: 'Saudi Arbia',
      company: "L'Oreal",
    },
    {
      name: 'Wade Warren',
      phone: '(671) 555-0110',
      email: 'dolars.champ@example.com',
      date: 'septemper 24 ,2017',
      country: 'Serpia',
      company: 'eBay',
    },
    {
      name: 'Devone lane',
      phone: '(209) 555-0104',
      email: 'sara.cruze@example.com',
      date: 'febraury 9 ,2015',
      country: 'Russian Federation',
      company: 'Gillete',
    },
    {
      name: 'Albert Flores',
      phone: '(808) 555-0111',
      email: 'danna.hill@example.com',
      date: 'Nuvamper 16 ,2014',
      country: 'Poland',
      company: 'Luis Vuitton',
    },
    {
      name: 'Jerome Bell',
      phone: '(505) 555-0125',
      email: 'tanya.Jerome@example.com',
      date: 'October 31 ,2017',
      country: 'Saudi Arbia',
      company: 'Facebook',
    },
  ];
  return heros;
};
